version: "3.2"
services:

  vending_app:
    restart: unless-stopped
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - published: ${SERVER_PORT:-15500}
        target: 15500
    environment:
      - JWT_SECRET=$JWT_SECRET
      - DB_HOST=mongo_db
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PWD=$DB_PWD
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_SECRET=$REDIS_SECRET
    # depends_on:
    #   - mongo_db
    links:
      - mongo_db
      - cache

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PWD
    ports:
      - "27017:27017"
    volumes:
      - vending_mongo:/data/db

  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    entrypoint: redis-server --appendonly yes
    volumes:
      - vending_cache:/data

volumes:
  vending_mongo:
  vending_cache:
    driver: local
